/*
 * Digitraffic Road API
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information. Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)   The service has a public Google-group [road.digitraffic.fi](https://groups.google.com/forum/#!forum/roaddigitrafficfi) for communication between developers, service administrators and Fintraffic. The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.   ### General notes of the API * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946. * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 2.94.0#e017ffd@2022-10-18T07:48:28+0000
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.tuni.monitor.roadapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.tuni.monitor.roadapi.model.CameraPresetData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Road wather station with sensor values
 */
@ApiModel(description = "Road wather station with sensor values")
@JsonPropertyOrder({
  CameraStationData.JSON_PROPERTY_ID,
  CameraStationData.JSON_PROPERTY_ROAD_STATION_ID,
  CameraStationData.JSON_PROPERTY_NEAREST_WEATHER_STATION_ID,
  CameraStationData.JSON_PROPERTY_CAMERA_PRESETS
})
public class CameraStationData {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_ROAD_STATION_ID = "roadStationId";
  private Long roadStationId;

  public static final String JSON_PROPERTY_NEAREST_WEATHER_STATION_ID = "nearestWeatherStationId";
  private Long nearestWeatherStationId;

  public static final String JSON_PROPERTY_CAMERA_PRESETS = "cameraPresets";
  private List<CameraPresetData> cameraPresets = null;

  public CameraStationData() {
  }

  public CameraStationData id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public CameraStationData roadStationId(Long roadStationId) {
    
    this.roadStationId = roadStationId;
    return this;
  }

   /**
   * Get roadStationId
   * @return roadStationId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ROAD_STATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getRoadStationId() {
    return roadStationId;
  }


  @JsonProperty(JSON_PROPERTY_ROAD_STATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRoadStationId(Long roadStationId) {
    this.roadStationId = roadStationId;
  }


  public CameraStationData nearestWeatherStationId(Long nearestWeatherStationId) {
    
    this.nearestWeatherStationId = nearestWeatherStationId;
    return this;
  }

   /**
   * Get nearestWeatherStationId
   * @return nearestWeatherStationId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NEAREST_WEATHER_STATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getNearestWeatherStationId() {
    return nearestWeatherStationId;
  }


  @JsonProperty(JSON_PROPERTY_NEAREST_WEATHER_STATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNearestWeatherStationId(Long nearestWeatherStationId) {
    this.nearestWeatherStationId = nearestWeatherStationId;
  }


  public CameraStationData cameraPresets(List<CameraPresetData> cameraPresets) {
    
    this.cameraPresets = cameraPresets;
    return this;
  }

  public CameraStationData addCameraPresetsItem(CameraPresetData cameraPresetsItem) {
    if (this.cameraPresets == null) {
      this.cameraPresets = new ArrayList<>();
    }
    this.cameraPresets.add(cameraPresetsItem);
    return this;
  }

   /**
   * Get cameraPresets
   * @return cameraPresets
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CAMERA_PRESETS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CameraPresetData> getCameraPresets() {
    return cameraPresets;
  }


  @JsonProperty(JSON_PROPERTY_CAMERA_PRESETS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCameraPresets(List<CameraPresetData> cameraPresets) {
    this.cameraPresets = cameraPresets;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CameraStationData cameraStationData = (CameraStationData) o;
    return Objects.equals(this.id, cameraStationData.id) &&
        Objects.equals(this.roadStationId, cameraStationData.roadStationId) &&
        Objects.equals(this.nearestWeatherStationId, cameraStationData.nearestWeatherStationId) &&
        Objects.equals(this.cameraPresets, cameraStationData.cameraPresets);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, roadStationId, nearestWeatherStationId, cameraPresets);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CameraStationData {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    roadStationId: ").append(toIndentedString(roadStationId)).append("\n");
    sb.append("    nearestWeatherStationId: ").append(toIndentedString(nearestWeatherStationId)).append("\n");
    sb.append("    cameraPresets: ").append(toIndentedString(cameraPresets)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

