/*
 * Digitraffic Road API
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information. Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)   The service has a public Google-group [road.digitraffic.fi](https://groups.google.com/forum/#!forum/roaddigitrafficfi) for communication between developers, service administrators and Fintraffic. The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.   ### General notes of the API * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946. * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 2.94.0#e017ffd@2022-10-18T07:48:28+0000
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.tuni.monitor.roadapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.tuni.monitor.roadapi.model.PresetHistoryPresence;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Image history presence for camera and it&#39;s presets at given time interval.
 */
@ApiModel(description = "Image history presence for camera and it's presets at given time interval.")
@JsonPropertyOrder({
  CameraHistoryPresence.JSON_PROPERTY_CAMERA_ID,
  CameraHistoryPresence.JSON_PROPERTY_HISTORY_PRESENT,
  CameraHistoryPresence.JSON_PROPERTY_PRESET_HISTORY_PRESENCES
})
public class CameraHistoryPresence {
  public static final String JSON_PROPERTY_CAMERA_ID = "cameraId";
  private String cameraId;

  public static final String JSON_PROPERTY_HISTORY_PRESENT = "historyPresent";
  private Boolean historyPresent;

  public static final String JSON_PROPERTY_PRESET_HISTORY_PRESENCES = "presetHistoryPresences";
  private List<PresetHistoryPresence> presetHistoryPresences = null;

  public CameraHistoryPresence() {
  }

  public CameraHistoryPresence cameraId(String cameraId) {
    
    this.cameraId = cameraId;
    return this;
  }

   /**
   * Camera id.
   * @return cameraId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Camera id.")
  @JsonProperty(JSON_PROPERTY_CAMERA_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCameraId() {
    return cameraId;
  }


  @JsonProperty(JSON_PROPERTY_CAMERA_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCameraId(String cameraId) {
    this.cameraId = cameraId;
  }


  public CameraHistoryPresence historyPresent(Boolean historyPresent) {
    
    this.historyPresent = historyPresent;
    return this;
  }

   /**
   * If true then there is image history present for the camera at given time interval.
   * @return historyPresent
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If true then there is image history present for the camera at given time interval.")
  @JsonProperty(JSON_PROPERTY_HISTORY_PRESENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHistoryPresent() {
    return historyPresent;
  }


  @JsonProperty(JSON_PROPERTY_HISTORY_PRESENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHistoryPresent(Boolean historyPresent) {
    this.historyPresent = historyPresent;
  }


  public CameraHistoryPresence presetHistoryPresences(List<PresetHistoryPresence> presetHistoryPresences) {
    
    this.presetHistoryPresences = presetHistoryPresences;
    return this;
  }

  public CameraHistoryPresence addPresetHistoryPresencesItem(PresetHistoryPresence presetHistoryPresencesItem) {
    if (this.presetHistoryPresences == null) {
      this.presetHistoryPresences = new ArrayList<>();
    }
    this.presetHistoryPresences.add(presetHistoryPresencesItem);
    return this;
  }

   /**
   * History statuses of the camera presets at given time interval.
   * @return presetHistoryPresences
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "History statuses of the camera presets at given time interval.")
  @JsonProperty(JSON_PROPERTY_PRESET_HISTORY_PRESENCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PresetHistoryPresence> getPresetHistoryPresences() {
    return presetHistoryPresences;
  }


  @JsonProperty(JSON_PROPERTY_PRESET_HISTORY_PRESENCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPresetHistoryPresences(List<PresetHistoryPresence> presetHistoryPresences) {
    this.presetHistoryPresences = presetHistoryPresences;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CameraHistoryPresence cameraHistoryPresence = (CameraHistoryPresence) o;
    return Objects.equals(this.cameraId, cameraHistoryPresence.cameraId) &&
        Objects.equals(this.historyPresent, cameraHistoryPresence.historyPresent) &&
        Objects.equals(this.presetHistoryPresences, cameraHistoryPresence.presetHistoryPresences);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cameraId, historyPresent, presetHistoryPresences);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CameraHistoryPresence {\n");
    sb.append("    cameraId: ").append(toIndentedString(cameraId)).append("\n");
    sb.append("    historyPresent: ").append(toIndentedString(historyPresent)).append("\n");
    sb.append("    presetHistoryPresences: ").append(toIndentedString(presetHistoryPresences)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

