/*
 * Digitraffic Road API
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information. Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)   The service has a public Google-group [road.digitraffic.fi](https://groups.google.com/forum/#!forum/roaddigitrafficfi) for communication between developers, service administrators and Fintraffic. The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.   ### General notes of the API * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946. * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 2.94.0#e017ffd@2022-10-18T07:48:28+0000
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.tuni.monitor.roadapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.tuni.monitor.roadapi.model.ExtensionType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CatalogueReference
 */
@JsonPropertyOrder({
  CatalogueReference.JSON_PROPERTY_KEY_CATALOGUE_REFERENCE,
  CatalogueReference.JSON_PROPERTY_CATALOGUE_REFERENCE_EXTENSION
})
public class CatalogueReference {
  public static final String JSON_PROPERTY_KEY_CATALOGUE_REFERENCE = "keyCatalogueReference";
  private String keyCatalogueReference;

  public static final String JSON_PROPERTY_CATALOGUE_REFERENCE_EXTENSION = "catalogueReferenceExtension";
  private ExtensionType catalogueReferenceExtension;

  public CatalogueReference() {
  }

  public CatalogueReference keyCatalogueReference(String keyCatalogueReference) {
    
    this.keyCatalogueReference = keyCatalogueReference;
    return this;
  }

   /**
   * Get keyCatalogueReference
   * @return keyCatalogueReference
  **/
 
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_KEY_CATALOGUE_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getKeyCatalogueReference() {
    return keyCatalogueReference;
  }


  @JsonProperty(JSON_PROPERTY_KEY_CATALOGUE_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKeyCatalogueReference(String keyCatalogueReference) {
    this.keyCatalogueReference = keyCatalogueReference;
  }


  public CatalogueReference catalogueReferenceExtension(ExtensionType catalogueReferenceExtension) {
    
    this.catalogueReferenceExtension = catalogueReferenceExtension;
    return this;
  }

   /**
   * Get catalogueReferenceExtension
   * @return catalogueReferenceExtension
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CATALOGUE_REFERENCE_EXTENSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ExtensionType getCatalogueReferenceExtension() {
    return catalogueReferenceExtension;
  }


  @JsonProperty(JSON_PROPERTY_CATALOGUE_REFERENCE_EXTENSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCatalogueReferenceExtension(ExtensionType catalogueReferenceExtension) {
    this.catalogueReferenceExtension = catalogueReferenceExtension;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CatalogueReference catalogueReference = (CatalogueReference) o;
    return Objects.equals(this.keyCatalogueReference, catalogueReference.keyCatalogueReference) &&
        Objects.equals(this.catalogueReferenceExtension, catalogueReference.catalogueReferenceExtension);
  }

  @Override
  public int hashCode() {
    return Objects.hash(keyCatalogueReference, catalogueReferenceExtension);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CatalogueReference {\n");
    sb.append("    keyCatalogueReference: ").append(toIndentedString(keyCatalogueReference)).append("\n");
    sb.append("    catalogueReferenceExtension: ").append(toIndentedString(catalogueReferenceExtension)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

