/*
 * Digitraffic Road API
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information. Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)   The service has a public Google-group [road.digitraffic.fi](https://groups.google.com/forum/#!forum/roaddigitrafficfi) for communication between developers, service administrators and Fintraffic. The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.   ### General notes of the API * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946. * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 2.94.0#e017ffd@2022-10-18T07:48:28+0000
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.tuni.monitor.roadapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.tuni.monitor.roadapi.model.ForecastSectionPropertiesV1;
import fi.tuni.monitor.roadapi.model.TrafficAnnouncementFeatureOldV3Geometry;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GeoJSON feature object of forecast section
 */
@ApiModel(description = "GeoJSON feature object of forecast section")
@JsonPropertyOrder({
  ForecastSectionFeatureV1.JSON_PROPERTY_TYPE,
  ForecastSectionFeatureV1.JSON_PROPERTY_ID,
  ForecastSectionFeatureV1.JSON_PROPERTY_GEOMETRY,
  ForecastSectionFeatureV1.JSON_PROPERTY_PROPERTIES
})
public class ForecastSectionFeatureV1 {
  public static final String JSON_PROPERTY_TYPE = "type";
  private String type;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_GEOMETRY = "geometry";
  private TrafficAnnouncementFeatureOldV3Geometry geometry;

  public static final String JSON_PROPERTY_PROPERTIES = "properties";
  private ForecastSectionPropertiesV1 properties;

  public ForecastSectionFeatureV1() {
  }

  public ForecastSectionFeatureV1 type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * GeoJSON Object Type
   * @return type
  **/
 
  @ApiModelProperty(required = true, value = "GeoJSON Object Type")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(String type) {
    this.type = type;
  }


  public ForecastSectionFeatureV1 id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Forecast section identifier ie. 00004_342_01435_0_274.569:  1. Road number 5 characters ie. 00004,  2. Road section 3 characters ie. 342,  3. Start distance 5 characters ie. 000,  4. Carriageway 1 character,  5. Measure value of link start point. Varying number of characters ie. 274.569,  Refers to Digiroad content at https://aineistot.vayla.fi/digiroad/
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Forecast section identifier ie. 00004_342_01435_0_274.569:  1. Road number 5 characters ie. 00004,  2. Road section 3 characters ie. 342,  3. Start distance 5 characters ie. 000,  4. Carriageway 1 character,  5. Measure value of link start point. Varying number of characters ie. 274.569,  Refers to Digiroad content at https://aineistot.vayla.fi/digiroad/")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public ForecastSectionFeatureV1 geometry(TrafficAnnouncementFeatureOldV3Geometry geometry) {
    
    this.geometry = geometry;
    return this;
  }

   /**
   * Get geometry
   * @return geometry
  **/
 
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_GEOMETRY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TrafficAnnouncementFeatureOldV3Geometry getGeometry() {
    return geometry;
  }


  @JsonProperty(JSON_PROPERTY_GEOMETRY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setGeometry(TrafficAnnouncementFeatureOldV3Geometry geometry) {
    this.geometry = geometry;
  }


  public ForecastSectionFeatureV1 properties(ForecastSectionPropertiesV1 properties) {
    
    this.properties = properties;
    return this;
  }

   /**
   * Get properties
   * @return properties
  **/
 
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ForecastSectionPropertiesV1 getProperties() {
    return properties;
  }


  @JsonProperty(JSON_PROPERTY_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProperties(ForecastSectionPropertiesV1 properties) {
    this.properties = properties;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ForecastSectionFeatureV1 forecastSectionFeatureV1 = (ForecastSectionFeatureV1) o;
    return Objects.equals(this.type, forecastSectionFeatureV1.type) &&
        Objects.equals(this.id, forecastSectionFeatureV1.id) &&
        Objects.equals(this.geometry, forecastSectionFeatureV1.geometry) &&
        Objects.equals(this.properties, forecastSectionFeatureV1.properties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, id, geometry, properties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ForecastSectionFeatureV1 {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    geometry: ").append(toIndentedString(geometry)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

