/*
 * Digitraffic Road API
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information. Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)   The service has a public Google-group [road.digitraffic.fi](https://groups.google.com/forum/#!forum/roaddigitrafficfi) for communication between developers, service administrators and Fintraffic. The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.   ### General notes of the API * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946. * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 2.94.0#e017ffd@2022-10-18T07:48:28+0000
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.tuni.monitor.roadapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.tuni.monitor.roadapi.model.RoadCondition;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ForecastSectionWeatherData
 */
@JsonPropertyOrder({
  ForecastSectionWeatherData.JSON_PROPERTY_ID,
  ForecastSectionWeatherData.JSON_PROPERTY_ROAD_CONDITIONS
})
public class ForecastSectionWeatherData {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_ROAD_CONDITIONS = "roadConditions";
  private List<RoadCondition> roadConditions = null;

  public ForecastSectionWeatherData() {
  }

  public ForecastSectionWeatherData id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * VERSION 1: Forecast section identifier 15 characters ie. 00004_112_000_0: &lt;br&gt; 1. Road number 5 characters ie. 00004, &lt;br&gt; 2. Road section 3 characters ie. 112, &lt;br&gt; 3. Road section version 3 characters ie. 000, &lt;br&gt; 4. Reserved for future needs 1 characters default 0 &lt;br&gt; &lt;br&gt; VERSION 2: Forecast section identifier ie. 00004_342_01435_0_274.569: &lt;br&gt; 1. Road number 5 characters ie. 00004, &lt;br&gt; 2. Road section 3 characters ie. 342, &lt;br&gt; 3. Start distance 5 characters ie. 000, &lt;br&gt; 4. Carriageway 1 character, &lt;br&gt; 5. Measure value of link start point. Varying number of characters ie. 274.569, &lt;br&gt; Refers to Digiroad content at https://aineistot.vayla.fi/digiroad/
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "VERSION 1: Forecast section identifier 15 characters ie. 00004_112_000_0: <br> 1. Road number 5 characters ie. 00004, <br> 2. Road section 3 characters ie. 112, <br> 3. Road section version 3 characters ie. 000, <br> 4. Reserved for future needs 1 characters default 0 <br> <br> VERSION 2: Forecast section identifier ie. 00004_342_01435_0_274.569: <br> 1. Road number 5 characters ie. 00004, <br> 2. Road section 3 characters ie. 342, <br> 3. Start distance 5 characters ie. 000, <br> 4. Carriageway 1 character, <br> 5. Measure value of link start point. Varying number of characters ie. 274.569, <br> Refers to Digiroad content at https://aineistot.vayla.fi/digiroad/")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public ForecastSectionWeatherData roadConditions(List<RoadCondition> roadConditions) {
    
    this.roadConditions = roadConditions;
    return this;
  }

  public ForecastSectionWeatherData addRoadConditionsItem(RoadCondition roadConditionsItem) {
    if (this.roadConditions == null) {
      this.roadConditions = new ArrayList<>();
    }
    this.roadConditions.add(roadConditionsItem);
    return this;
  }

   /**
   * Road conditions data forecast section
   * @return roadConditions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Road conditions data forecast section")
  @JsonProperty(JSON_PROPERTY_ROAD_CONDITIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<RoadCondition> getRoadConditions() {
    return roadConditions;
  }


  @JsonProperty(JSON_PROPERTY_ROAD_CONDITIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRoadConditions(List<RoadCondition> roadConditions) {
    this.roadConditions = roadConditions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ForecastSectionWeatherData forecastSectionWeatherData = (ForecastSectionWeatherData) o;
    return Objects.equals(this.id, forecastSectionWeatherData.id) &&
        Objects.equals(this.roadConditions, forecastSectionWeatherData.roadConditions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, roadConditions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ForecastSectionWeatherData {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    roadConditions: ").append(toIndentedString(roadConditions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

