/*
 * Digitraffic Road API
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information. Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)   The service has a public Google-group [road.digitraffic.fi](https://groups.google.com/forum/#!forum/roaddigitrafficfi) for communication between developers, service administrators and Fintraffic. The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.   ### General notes of the API * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946. * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 2.94.0#e017ffd@2022-10-18T07:48:28+0000
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.tuni.monitor.roadapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Maintenance tracking task
 */
@ApiModel(description = "Maintenance tracking task")
@JsonPropertyOrder({
  MaintenanceTrackingTaskOld.JSON_PROPERTY_ID,
  MaintenanceTrackingTaskOld.JSON_PROPERTY_NAME_FI,
  MaintenanceTrackingTaskOld.JSON_PROPERTY_NAME_EN,
  MaintenanceTrackingTaskOld.JSON_PROPERTY_NAME_SV
})
public class MaintenanceTrackingTaskOld {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_NAME_FI = "nameFi";
  private String nameFi;

  public static final String JSON_PROPERTY_NAME_EN = "nameEn";
  private String nameEn;

  public static final String JSON_PROPERTY_NAME_SV = "nameSv";
  private String nameSv;

  public MaintenanceTrackingTaskOld() {
  }

  public MaintenanceTrackingTaskOld id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public MaintenanceTrackingTaskOld nameFi(String nameFi) {
    
    this.nameFi = nameFi;
    return this;
  }

   /**
   * Get nameFi
   * @return nameFi
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME_FI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNameFi() {
    return nameFi;
  }


  @JsonProperty(JSON_PROPERTY_NAME_FI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNameFi(String nameFi) {
    this.nameFi = nameFi;
  }


  public MaintenanceTrackingTaskOld nameEn(String nameEn) {
    
    this.nameEn = nameEn;
    return this;
  }

   /**
   * Get nameEn
   * @return nameEn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME_EN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNameEn() {
    return nameEn;
  }


  @JsonProperty(JSON_PROPERTY_NAME_EN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNameEn(String nameEn) {
    this.nameEn = nameEn;
  }


  public MaintenanceTrackingTaskOld nameSv(String nameSv) {
    
    this.nameSv = nameSv;
    return this;
  }

   /**
   * Get nameSv
   * @return nameSv
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME_SV)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNameSv() {
    return nameSv;
  }


  @JsonProperty(JSON_PROPERTY_NAME_SV)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNameSv(String nameSv) {
    this.nameSv = nameSv;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MaintenanceTrackingTaskOld maintenanceTrackingTaskOld = (MaintenanceTrackingTaskOld) o;
    return Objects.equals(this.id, maintenanceTrackingTaskOld.id) &&
        Objects.equals(this.nameFi, maintenanceTrackingTaskOld.nameFi) &&
        Objects.equals(this.nameEn, maintenanceTrackingTaskOld.nameEn) &&
        Objects.equals(this.nameSv, maintenanceTrackingTaskOld.nameSv);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, nameFi, nameEn, nameSv);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MaintenanceTrackingTaskOld {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    nameFi: ").append(toIndentedString(nameFi)).append("\n");
    sb.append("    nameEn: ").append(toIndentedString(nameEn)).append("\n");
    sb.append("    nameSv: ").append(toIndentedString(nameSv)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

