/*
 * Digitraffic Road API
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information. Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)   The service has a public Google-group [road.digitraffic.fi](https://groups.google.com/forum/#!forum/roaddigitrafficfi) for communication between developers, service administrators and Fintraffic. The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.   ### General notes of the API * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946. * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 2.94.0#e017ffd@2022-10-18T07:48:28+0000
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.tuni.monitor.roadapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.tuni.monitor.roadapi.model.Node;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * NamedNodeMap
 */
@JsonPropertyOrder({
  NamedNodeMap.JSON_PROPERTY_NAMED_ITEM,
  NamedNodeMap.JSON_PROPERTY_NAMED_ITEM_N_S,
  NamedNodeMap.JSON_PROPERTY_LENGTH
})
public class NamedNodeMap {
  public static final String JSON_PROPERTY_NAMED_ITEM = "namedItem";
  private Node namedItem;

  public static final String JSON_PROPERTY_NAMED_ITEM_N_S = "namedItemNS";
  private Node namedItemNS;

  public static final String JSON_PROPERTY_LENGTH = "length";
  private Integer length;

  public NamedNodeMap() {
  }

  public NamedNodeMap namedItem(Node namedItem) {
    
    this.namedItem = namedItem;
    return this;
  }

   /**
   * Get namedItem
   * @return namedItem
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAMED_ITEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Node getNamedItem() {
    return namedItem;
  }


  @JsonProperty(JSON_PROPERTY_NAMED_ITEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNamedItem(Node namedItem) {
    this.namedItem = namedItem;
  }


  public NamedNodeMap namedItemNS(Node namedItemNS) {
    
    this.namedItemNS = namedItemNS;
    return this;
  }

   /**
   * Get namedItemNS
   * @return namedItemNS
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAMED_ITEM_N_S)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Node getNamedItemNS() {
    return namedItemNS;
  }


  @JsonProperty(JSON_PROPERTY_NAMED_ITEM_N_S)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNamedItemNS(Node namedItemNS) {
    this.namedItemNS = namedItemNS;
  }


  public NamedNodeMap length(Integer length) {
    
    this.length = length;
    return this;
  }

   /**
   * Get length
   * @return length
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getLength() {
    return length;
  }


  @JsonProperty(JSON_PROPERTY_LENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLength(Integer length) {
    this.length = length;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NamedNodeMap namedNodeMap = (NamedNodeMap) o;
    return Objects.equals(this.namedItem, namedNodeMap.namedItem) &&
        Objects.equals(this.namedItemNS, namedNodeMap.namedItemNS) &&
        Objects.equals(this.length, namedNodeMap.length);
  }

  @Override
  public int hashCode() {
    return Objects.hash(namedItem, namedItemNS, length);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NamedNodeMap {\n");
    sb.append("    namedItem: ").append(toIndentedString(namedItem)).append("\n");
    sb.append("    namedItemNS: ").append(toIndentedString(namedItemNS)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

