/*
 * Digitraffic Road API
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information. Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)   The service has a public Google-group [road.digitraffic.fi](https://groups.google.com/forum/#!forum/roaddigitrafficfi) for communication between developers, service administrators and Fintraffic. The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.   ### General notes of the API * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946. * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 2.94.0#e017ffd@2022-10-18T07:48:28+0000
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.tuni.monitor.roadapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Image history status for preset at given time interval.
 */
@ApiModel(description = "Image history status for preset at given time interval.")
@JsonPropertyOrder({
  PresetHistoryPresence.JSON_PROPERTY_PRESET_ID,
  PresetHistoryPresence.JSON_PROPERTY_HISTORY_PRESENT
})
public class PresetHistoryPresence {
  public static final String JSON_PROPERTY_PRESET_ID = "presetId";
  private String presetId;

  public static final String JSON_PROPERTY_HISTORY_PRESENT = "historyPresent";
  private Boolean historyPresent;

  public PresetHistoryPresence() {
  }

  public PresetHistoryPresence presetId(String presetId) {
    
    this.presetId = presetId;
    return this;
  }

   /**
   * Camera preset id
   * @return presetId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Camera preset id")
  @JsonProperty(JSON_PROPERTY_PRESET_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPresetId() {
    return presetId;
  }


  @JsonProperty(JSON_PROPERTY_PRESET_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPresetId(String presetId) {
    this.presetId = presetId;
  }


  public PresetHistoryPresence historyPresent(Boolean historyPresent) {
    
    this.historyPresent = historyPresent;
    return this;
  }

   /**
   * If true then there is image history present for the preset at given time interval.
   * @return historyPresent
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If true then there is image history present for the preset at given time interval.")
  @JsonProperty(JSON_PROPERTY_HISTORY_PRESENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHistoryPresent() {
    return historyPresent;
  }


  @JsonProperty(JSON_PROPERTY_HISTORY_PRESENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHistoryPresent(Boolean historyPresent) {
    this.historyPresent = historyPresent;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PresetHistoryPresence presetHistoryPresence = (PresetHistoryPresence) o;
    return Objects.equals(this.presetId, presetHistoryPresence.presetId) &&
        Objects.equals(this.historyPresent, presetHistoryPresence.historyPresent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(presetId, historyPresent);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PresetHistoryPresence {\n");
    sb.append("    presetId: ").append(toIndentedString(presetId)).append("\n");
    sb.append("    historyPresent: ").append(toIndentedString(historyPresent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

