/*
 * Digitraffic Road API
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information. Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)   The service has a public Google-group [road.digitraffic.fi](https://groups.google.com/forum/#!forum/roaddigitrafficfi) for communication between developers, service administrators and Fintraffic. The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.   ### General notes of the API * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946. * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 2.94.0#e017ffd@2022-10-18T07:48:28+0000
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.tuni.monitor.roadapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * TMS Stations sensor constant values
 */
@ApiModel(description = "TMS Stations sensor constant values")
@JsonPropertyOrder({
  SensorConstantValue.JSON_PROPERTY_NAME,
  SensorConstantValue.JSON_PROPERTY_VALUE,
  SensorConstantValue.JSON_PROPERTY_VALID_FROM,
  SensorConstantValue.JSON_PROPERTY_VALID_TO
})
@JsonTypeName("Sensor constant value")
public class SensorConstantValue {
  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_VALUE = "value";
  private Integer value;

  public static final String JSON_PROPERTY_VALID_FROM = "validFrom";
  private String validFrom;

  public static final String JSON_PROPERTY_VALID_TO = "validTo";
  private String validTo;

  public SensorConstantValue() {
  }

  public SensorConstantValue name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name of the sensor constant
   * @return name
  **/
 
  @ApiModelProperty(required = true, value = "Name of the sensor constant")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  public SensorConstantValue value(Integer value) {
    
    this.value = value;
    return this;
  }

   /**
   * Value of the sensor constant
   * @return value
  **/
 
  @ApiModelProperty(required = true, value = "Value of the sensor constant")
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getValue() {
    return value;
  }


  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setValue(Integer value) {
    this.value = value;
  }


  public SensorConstantValue validFrom(String validFrom) {
    
    this.validFrom = validFrom;
    return this;
  }

   /**
   * Validity start in format mm-dd ie. value 01-31 is 31th of January
   * @return validFrom
  **/
 
  @ApiModelProperty(required = true, value = "Validity start in format mm-dd ie. value 01-31 is 31th of January")
  @JsonProperty(JSON_PROPERTY_VALID_FROM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getValidFrom() {
    return validFrom;
  }


  @JsonProperty(JSON_PROPERTY_VALID_FROM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setValidFrom(String validFrom) {
    this.validFrom = validFrom;
  }


  public SensorConstantValue validTo(String validTo) {
    
    this.validTo = validTo;
    return this;
  }

   /**
   * Validity end in format mm-dd ie. value 01-31 is 31th of January
   * @return validTo
  **/
 
  @ApiModelProperty(required = true, value = "Validity end in format mm-dd ie. value 01-31 is 31th of January")
  @JsonProperty(JSON_PROPERTY_VALID_TO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getValidTo() {
    return validTo;
  }


  @JsonProperty(JSON_PROPERTY_VALID_TO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setValidTo(String validTo) {
    this.validTo = validTo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SensorConstantValue sensorConstantValue = (SensorConstantValue) o;
    return Objects.equals(this.name, sensorConstantValue.name) &&
        Objects.equals(this.value, sensorConstantValue.value) &&
        Objects.equals(this.validFrom, sensorConstantValue.validFrom) &&
        Objects.equals(this.validTo, sensorConstantValue.validTo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, value, validFrom, validTo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SensorConstantValue {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    validFrom: ").append(toIndentedString(validFrom)).append("\n");
    sb.append("    validTo: ").append(toIndentedString(validTo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

