/*
 * Digitraffic Road API
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information. Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)   The service has a public Google-group [road.digitraffic.fi](https://groups.google.com/forum/#!forum/roaddigitrafficfi) for communication between developers, service administrators and Fintraffic. The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.   ### General notes of the API * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946. * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 2.94.0#e017ffd@2022-10-18T07:48:28+0000
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.tuni.monitor.roadapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.tuni.monitor.roadapi.model.D2LogicalModel;
import fi.tuni.monitor.roadapi.model.ObservationTimeType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * TimestampedTrafficDisorderDatex2
 */
@JsonPropertyOrder({
  TimestampedTrafficDisorderDatex2.JSON_PROPERTY_PUBLISHED,
  TimestampedTrafficDisorderDatex2.JSON_PROPERTY_D2_LOGICAL_MODEL
})
public class TimestampedTrafficDisorderDatex2 {
  public static final String JSON_PROPERTY_PUBLISHED = "published";
  private ObservationTimeType published;

  public static final String JSON_PROPERTY_D2_LOGICAL_MODEL = "d2LogicalModel";
  private D2LogicalModel d2LogicalModel;

  public TimestampedTrafficDisorderDatex2() {
  }

  public TimestampedTrafficDisorderDatex2 published(ObservationTimeType published) {
    
    this.published = published;
    return this;
  }

   /**
   * Get published
   * @return published
  **/
 
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_PUBLISHED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ObservationTimeType getPublished() {
    return published;
  }


  @JsonProperty(JSON_PROPERTY_PUBLISHED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPublished(ObservationTimeType published) {
    this.published = published;
  }


  public TimestampedTrafficDisorderDatex2 d2LogicalModel(D2LogicalModel d2LogicalModel) {
    
    this.d2LogicalModel = d2LogicalModel;
    return this;
  }

   /**
   * Get d2LogicalModel
   * @return d2LogicalModel
  **/
 
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_D2_LOGICAL_MODEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public D2LogicalModel getD2LogicalModel() {
    return d2LogicalModel;
  }


  @JsonProperty(JSON_PROPERTY_D2_LOGICAL_MODEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setD2LogicalModel(D2LogicalModel d2LogicalModel) {
    this.d2LogicalModel = d2LogicalModel;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimestampedTrafficDisorderDatex2 timestampedTrafficDisorderDatex2 = (TimestampedTrafficDisorderDatex2) o;
    return Objects.equals(this.published, timestampedTrafficDisorderDatex2.published) &&
        Objects.equals(this.d2LogicalModel, timestampedTrafficDisorderDatex2.d2LogicalModel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(published, d2LogicalModel);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimestampedTrafficDisorderDatex2 {\n");
    sb.append("    published: ").append(toIndentedString(published)).append("\n");
    sb.append("    d2LogicalModel: ").append(toIndentedString(d2LogicalModel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

