/*
 * Digitraffic Road API
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information. Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)   The service has a public Google-group [road.digitraffic.fi](https://groups.google.com/forum/#!forum/roaddigitrafficfi) for communication between developers, service administrators and Fintraffic. The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.   ### General notes of the API * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946. * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 2.94.0#e017ffd@2022-10-18T07:48:28+0000
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.tuni.monitor.roadapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.tuni.monitor.roadapi.model.LocationDetailsOldV2;
import fi.tuni.monitor.roadapi.model.LocationOldV2;
import fi.tuni.monitor.roadapi.model.TimeAndDurationOldV2;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Announcement time and duration
 */
@ApiModel(description = "Announcement time and duration")
@JsonPropertyOrder({
  TrafficAnnouncementOldV2.JSON_PROPERTY_LANGUAGE,
  TrafficAnnouncementOldV2.JSON_PROPERTY_TITLE,
  TrafficAnnouncementOldV2.JSON_PROPERTY_LOCATION,
  TrafficAnnouncementOldV2.JSON_PROPERTY_LOCATION_DETAILS,
  TrafficAnnouncementOldV2.JSON_PROPERTY_FEATURES,
  TrafficAnnouncementOldV2.JSON_PROPERTY_COMMENT,
  TrafficAnnouncementOldV2.JSON_PROPERTY_TIME_AND_DURATION,
  TrafficAnnouncementOldV2.JSON_PROPERTY_ADDITIONAL_INFORMATION,
  TrafficAnnouncementOldV2.JSON_PROPERTY_SENDER
})
@JsonTypeName("TrafficAnnouncement_OldV2")
public class TrafficAnnouncementOldV2 {
  public static final String JSON_PROPERTY_LANGUAGE = "language";
  private String language;

  public static final String JSON_PROPERTY_TITLE = "title";
  private String title;

  public static final String JSON_PROPERTY_LOCATION = "location";
  private LocationOldV2 location;

  public static final String JSON_PROPERTY_LOCATION_DETAILS = "locationDetails";
  private LocationDetailsOldV2 locationDetails;

  public static final String JSON_PROPERTY_FEATURES = "features";
  private List<String> features = null;

  public static final String JSON_PROPERTY_COMMENT = "comment";
  private String comment;

  public static final String JSON_PROPERTY_TIME_AND_DURATION = "timeAndDuration";
  private TimeAndDurationOldV2 timeAndDuration;

  public static final String JSON_PROPERTY_ADDITIONAL_INFORMATION = "additionalInformation";
  private String additionalInformation;

  public static final String JSON_PROPERTY_SENDER = "sender";
  private String sender;

  public TrafficAnnouncementOldV2() {
  }

  public TrafficAnnouncementOldV2 language(String language) {
    
    this.language = language;
    return this;
  }

   /**
   * Language of the announcement eq. fi, sv, en or ru. A subset of ISO 639-1.
   * @return language
  **/
 
  @ApiModelProperty(required = true, value = "Language of the announcement eq. fi, sv, en or ru. A subset of ISO 639-1.")
  @JsonProperty(JSON_PROPERTY_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLanguage() {
    return language;
  }


  @JsonProperty(JSON_PROPERTY_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLanguage(String language) {
    this.language = language;
  }


  public TrafficAnnouncementOldV2 title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Short description about the situation
   * @return title
  **/
 
  @ApiModelProperty(required = true, value = "Short description about the situation")
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTitle() {
    return title;
  }


  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTitle(String title) {
    this.title = title;
  }


  public TrafficAnnouncementOldV2 location(LocationOldV2 location) {
    
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocationOldV2 getLocation() {
    return location;
  }


  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocation(LocationOldV2 location) {
    this.location = location;
  }


  public TrafficAnnouncementOldV2 locationDetails(LocationDetailsOldV2 locationDetails) {
    
    this.locationDetails = locationDetails;
    return this;
  }

   /**
   * Get locationDetails
   * @return locationDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LOCATION_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocationDetailsOldV2 getLocationDetails() {
    return locationDetails;
  }


  @JsonProperty(JSON_PROPERTY_LOCATION_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocationDetails(LocationDetailsOldV2 locationDetails) {
    this.locationDetails = locationDetails;
  }


  public TrafficAnnouncementOldV2 features(List<String> features) {
    
    this.features = features;
    return this;
  }

  public TrafficAnnouncementOldV2 addFeaturesItem(String featuresItem) {
    if (this.features == null) {
      this.features = new ArrayList<>();
    }
    this.features.add(featuresItem);
    return this;
  }

   /**
   * Features of the announcement
   * @return features
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Features of the announcement")
  @JsonProperty(JSON_PROPERTY_FEATURES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getFeatures() {
    return features;
  }


  @JsonProperty(JSON_PROPERTY_FEATURES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFeatures(List<String> features) {
    this.features = features;
  }


  public TrafficAnnouncementOldV2 comment(String comment) {
    
    this.comment = comment;
    return this;
  }

   /**
   * Free comment
   * @return comment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Free comment")
  @JsonProperty(JSON_PROPERTY_COMMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComment() {
    return comment;
  }


  @JsonProperty(JSON_PROPERTY_COMMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComment(String comment) {
    this.comment = comment;
  }


  public TrafficAnnouncementOldV2 timeAndDuration(TimeAndDurationOldV2 timeAndDuration) {
    
    this.timeAndDuration = timeAndDuration;
    return this;
  }

   /**
   * Get timeAndDuration
   * @return timeAndDuration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TIME_AND_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TimeAndDurationOldV2 getTimeAndDuration() {
    return timeAndDuration;
  }


  @JsonProperty(JSON_PROPERTY_TIME_AND_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeAndDuration(TimeAndDurationOldV2 timeAndDuration) {
    this.timeAndDuration = timeAndDuration;
  }


  public TrafficAnnouncementOldV2 additionalInformation(String additionalInformation) {
    
    this.additionalInformation = additionalInformation;
    return this;
  }

   /**
   * Additional information.
   * @return additionalInformation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Additional information.")
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAdditionalInformation() {
    return additionalInformation;
  }


  @JsonProperty(JSON_PROPERTY_ADDITIONAL_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdditionalInformation(String additionalInformation) {
    this.additionalInformation = additionalInformation;
  }


  public TrafficAnnouncementOldV2 sender(String sender) {
    
    this.sender = sender;
    return this;
  }

   /**
   * Name of the sender
   * @return sender
  **/
 
  @ApiModelProperty(required = true, value = "Name of the sender")
  @JsonProperty(JSON_PROPERTY_SENDER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSender() {
    return sender;
  }


  @JsonProperty(JSON_PROPERTY_SENDER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSender(String sender) {
    this.sender = sender;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrafficAnnouncementOldV2 trafficAnnouncementOldV2 = (TrafficAnnouncementOldV2) o;
    return Objects.equals(this.language, trafficAnnouncementOldV2.language) &&
        Objects.equals(this.title, trafficAnnouncementOldV2.title) &&
        Objects.equals(this.location, trafficAnnouncementOldV2.location) &&
        Objects.equals(this.locationDetails, trafficAnnouncementOldV2.locationDetails) &&
        Objects.equals(this.features, trafficAnnouncementOldV2.features) &&
        Objects.equals(this.comment, trafficAnnouncementOldV2.comment) &&
        Objects.equals(this.timeAndDuration, trafficAnnouncementOldV2.timeAndDuration) &&
        Objects.equals(this.additionalInformation, trafficAnnouncementOldV2.additionalInformation) &&
        Objects.equals(this.sender, trafficAnnouncementOldV2.sender);
  }

  @Override
  public int hashCode() {
    return Objects.hash(language, title, location, locationDetails, features, comment, timeAndDuration, additionalInformation, sender);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrafficAnnouncementOldV2 {\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    locationDetails: ").append(toIndentedString(locationDetails)).append("\n");
    sb.append("    features: ").append(toIndentedString(features)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    timeAndDuration: ").append(toIndentedString(timeAndDuration)).append("\n");
    sb.append("    additionalInformation: ").append(toIndentedString(additionalInformation)).append("\n");
    sb.append("    sender: ").append(toIndentedString(sender)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

