/*
 * Digitraffic Road API
 * [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information. Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)   The service has a public Google-group [road.digitraffic.fi](https://groups.google.com/forum/#!forum/roaddigitrafficfi) for communication between developers, service administrators and Fintraffic. The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.   ### General notes of the API * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946. * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.
 *
 * The version of the OpenAPI document: 2.94.0#e017ffd@2022-10-18T07:48:28+0000
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.tuni.monitor.roadapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.tuni.monitor.roadapi.model.WeathercamPresetPublicityHistoryV1;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Weathercam station presets publicity changes
 */
@ApiModel(description = "Weathercam station presets publicity changes")
@JsonPropertyOrder({
  WeathercamStationPresetsPublicityHistoryV1.JSON_PROPERTY_ID,
  WeathercamStationPresetsPublicityHistoryV1.JSON_PROPERTY_DATA_UPDATED_TIME,
  WeathercamStationPresetsPublicityHistoryV1.JSON_PROPERTY_PRESETS
})
public class WeathercamStationPresetsPublicityHistoryV1 {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_DATA_UPDATED_TIME = "dataUpdatedTime";
  private OffsetDateTime dataUpdatedTime;

  public static final String JSON_PROPERTY_PRESETS = "presets";
  private List<WeathercamPresetPublicityHistoryV1> presets = new ArrayList<>();

  public WeathercamStationPresetsPublicityHistoryV1() {
  }

  public WeathercamStationPresetsPublicityHistoryV1 id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Id of the road station
   * @return id
  **/
 
  @ApiModelProperty(required = true, value = "Id of the road station")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(String id) {
    this.id = id;
  }


  public WeathercamStationPresetsPublicityHistoryV1 dataUpdatedTime(OffsetDateTime dataUpdatedTime) {
    
    this.dataUpdatedTime = dataUpdatedTime;
    return this;
  }

   /**
   * Time when data was last updated
   * @return dataUpdatedTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Time when data was last updated")
  @JsonProperty(JSON_PROPERTY_DATA_UPDATED_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDataUpdatedTime() {
    return dataUpdatedTime;
  }


  @JsonProperty(JSON_PROPERTY_DATA_UPDATED_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDataUpdatedTime(OffsetDateTime dataUpdatedTime) {
    this.dataUpdatedTime = dataUpdatedTime;
  }


  public WeathercamStationPresetsPublicityHistoryV1 presets(List<WeathercamPresetPublicityHistoryV1> presets) {
    
    this.presets = presets;
    return this;
  }

  public WeathercamStationPresetsPublicityHistoryV1 addPresetsItem(WeathercamPresetPublicityHistoryV1 presetsItem) {
    this.presets.add(presetsItem);
    return this;
  }

   /**
   * Id of the weathercam station
   * @return presets
  **/
 
  @ApiModelProperty(required = true, value = "Id of the weathercam station")
  @JsonProperty(JSON_PROPERTY_PRESETS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<WeathercamPresetPublicityHistoryV1> getPresets() {
    return presets;
  }


  @JsonProperty(JSON_PROPERTY_PRESETS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPresets(List<WeathercamPresetPublicityHistoryV1> presets) {
    this.presets = presets;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WeathercamStationPresetsPublicityHistoryV1 weathercamStationPresetsPublicityHistoryV1 = (WeathercamStationPresetsPublicityHistoryV1) o;
    return Objects.equals(this.id, weathercamStationPresetsPublicityHistoryV1.id) &&
        Objects.equals(this.dataUpdatedTime, weathercamStationPresetsPublicityHistoryV1.dataUpdatedTime) &&
        Objects.equals(this.presets, weathercamStationPresetsPublicityHistoryV1.presets);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, dataUpdatedTime, presets);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WeathercamStationPresetsPublicityHistoryV1 {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    dataUpdatedTime: ").append(toIndentedString(dataUpdatedTime)).append("\n");
    sb.append("    presets: ").append(toIndentedString(presets)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

